export default  {
    "TOGGLE_PROFILE_MENU":"TOGGLE_PROFILE_MENU",
    "SET_PROFILE_MENU_OPEN":"SET_PROFILE_MENU_OPEN",
    "SET_PROFILE_MENU_CLOSE":"SET_PROFILE_MENU_CLOSE",

    "TOGGLE_BLUR":"TOGGLE BLUR",
    "SET_BLUR_ON":"SET_BLUR_ON",
    "SET_BLUR_OFF" :"SET_BLUR_OFF",

    "SET_SIGN_OUT_BOX_OPEN":"SET_SIGN_OUT_BOX_OPEN",
    "SET_SIGN_OUT_BOX_CLOSE":"SET_SIGN_OUT_BOX_CLOSE",

    "SET_PAGE_Y_TOP":"SET_PAGE_Y_TOP",
}