const userActionType = {
"SIGN_IN_START":"SIGN_IN_START",
"SIGN_IN_SUCCESS":"SIGN_IN_SUCCESS",
"SIGN_IN_FAILURE":"SIGN_IN_FAILURE",
"SIGN_IN_ERROR_CLEAR":"SIGN_IN_ERROR_CLEAR",

"CHECK_SESSION_START":"CHECK_SESSION_START",
"CHECK_SESSION_SUCCESS":"CHECK_SESSION_SUCCESS",
"CHECK_SESSION_FAILURE":"CHECK_SESSION_FAILURE",
"SET_UNSUBSCRIBER":"SET_UNSUBSCRIBER",

"SIGN_OUT_START":"SIGN_OUT_START",
"SIGN_OUT_SUCCESS":"SIGN_OUT_SUCCESS",
"SIGN_OUT_FAILURE":"SIGN_OUT_FAILURE",
"SIGN_OUT_ERROR_CLEAR":"SIGN_OUT_ERROR_CLEAR",

"SIGN_UP_START":"SIGN_UP_START",
"SIGN_UP_SUCCESS":"SIGN_UP_SUCCESS",
"SIGN_UP_FAILURE":"SIGN_UP_FAILURE",
"SIGN_UP_ERROR_CLEAR":"SIGN_UP_ERROR_CLEAR",

"SET_CURRENT_ITEM":"SET_CURRENT_ITEM",
}

export default userActionType; 