export default {
"FETCH_EVENTS_START":"FETCH_EVENTS_START",
"FETCH_EVENTS_FAILURE":"FETCH_EVENTS_FAILURE",
"FETCH_EVENTS_SUCCESS":"FETCH_EVENTS_SUCCESS",

"POST_TASK_START":"POST_TASK_START",
"POST_TASK_FAILURE":"POST_TASK_FAILURE",
"POST_TASK_SUCCESS":"POST_TASK_SUCCESS",

"CLEAR_TASK":"CLEAR_TASK",
};